Repository themeum/tutor, pull requests merged in 2024-07, with the labels that each got.

#750 [FE] All questions types
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/OpenEndedAndShortAnswer.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/layouts/Navigator.tsx
  assets/react/v3/entries/course-builder/components/modals/AddLessonModal.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/atoms/Button.tsx
  assets/react/v3/shared/atoms/ImageInput.tsx
  assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
  assets/react/v3/shared/components/fields/FormImageInput.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
  assets/react/v3/shared/components/fields/FormQuestionTitle.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/molecules/DropdownButton.tsx
Labels: v3

#798 Added course ID parameter to product details query
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
Labels: v3

#795 chore: Comment out unused Notebook component in Layout.tsx
  assets/react/v3/entries/course-builder/components/layouts/Layout.tsx
Labels: v3

#803 Implemented course instructor api
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/services/users.ts
Labels: v3

#797 Implemented Certificate design
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/CertificateCard.tsx
  assets/react/v3/entries/course-builder/config/routes.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/pages/Certificate.tsx
  assets/react/v3/shared/config/icon-list.ts
Labels: v3

#801 Ecommerce Database Schema Design
  classes/Admin.php
  classes/Tutor.php
  composer.json
  ecommerce/OrderController.php
  models/OrderModel.php
  views/pages/ecommerce/order-list.php
Labels: v3

#796 Implemented the course details page with mock data
  .vscode/settings.json
  assets/images/orders/course-placeholder.png
  assets/react/v3/entries/order-details/atoms/Badge.tsx
  assets/react/v3/entries/order-details/components/App.tsx
  assets/react/v3/entries/order-details/components/layout/Main.tsx
  assets/react/v3/entries/order-details/components/layout/Topbar.tsx
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/components/order/Notes.tsx
  assets/react/v3/entries/order-details/components/order/OrderItem.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/components/order/Student.tsx
  assets/react/v3/entries/order-details/components/order/Summary.tsx
  assets/react/v3/entries/order-details/contexts/order-context.tsx
  assets/react/v3/entries/order-details/index.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/atoms/Avatar.tsx
  assets/react/v3/shared/atoms/Badge.tsx
  assets/react/v3/shared/atoms/Box.tsx
  assets/react/v3/shared/atoms/TutorBadge.tsx
  assets/react/v3/shared/components/Container.tsx
  assets/react/v3/shared/config/config.ts
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/config/styles.ts
  assets/react/v3/shared/molecules/Card.tsx
  assets/react/v3/shared/utils/api.ts
  assets/react/v3/shared/utils/currency.ts
  assets/react/v3/shared/utils/endpoints.ts
  assets/react/v3/shared/utils/style-utils.ts
  assets/react/v3/shared/utils/types.ts
  classes/Admin.php
  tsconfig.json
  views/pages/order-details.php
  webpack.config.js
Labels: v3

#807 Feat connected Tutor certificate to frontend
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/CertificateCard.tsx
  assets/react/v3/entries/course-builder/components/modals/AddLessonModal.tsx
  assets/react/v3/entries/course-builder/components/modals/CertificatePreviewModal.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/config/config.ts
Labels: v3

#800 Add the discount modal (design only)
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/shared/atoms/Button.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/config/styles.ts
  assets/react/v3/shared/utils/style-utils.ts
  classes/Admin.php
Labels: v3

#787 [FE] Create the video field
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/layouts/Header.tsx
  assets/react/v3/entries/course-builder/components/modals/AddLessonModal.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/atoms/ImageInput.tsx
  assets/react/v3/shared/components/fields/FormImageInput.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/config/config.ts
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/hooks/usePortalPopover.tsx
  assets/react/v3/shared/molecules/ConfirmationPopover.tsx
  assets/react/v3/shared/utils/util.ts
  classes/Course.php
Labels: v3

#813 Tutor attachment api integration
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormFileUploader.tsx
  assets/react/v3/shared/components/fields/FormImageInput.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
Labels: v3

#815 WP Editor support
  classes/Course.php
Labels: v3

#816 Feat: connected zoom api
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/LiveClass.tsx
  assets/react/v3/entries/course-builder/components/additional/MeetingCard.tsx
  assets/react/v3/entries/course-builder/components/additional/MeetingForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormDateInput.tsx
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/config/icon-list.ts
Labels: v3

#818 functionality updated, database updated
  classes/Tutor.php
  ecommerce/OrderController.php
  helpers/QueryHelper.php
  models/OrderModel.php
Labels: v3

#823 Tutor course builder flow implemented
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/CertificateCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/layouts/Header.tsx
  assets/react/v3/entries/course-builder/components/layouts/Navigator.tsx
  assets/react/v3/entries/course-builder/components/layouts/Tracker.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormCoursePrerequisites.tsx
  assets/react/v3/shared/components/fields/FormDateInput.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
  assets/react/v3/shared/components/fields/FormFileUploader.tsx
  assets/react/v3/shared/components/fields/FormInputWithContent.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/molecules/DropdownButton.tsx
Labels: v3

#817 Order API's Listing, Searching, Sorting & Query Helper Methods
  assets/react/admin-dashboard/segments/filter.js
  classes/Admin.php
  classes/Tutor.php
  ecommerce/CouponController.php
  ecommerce/Init.php
  ecommerce/OrderController.php
  helpers/QueryHelper.php
  includes/translate-text.php
  includes/tutor-general-functions.php
  models/CouponModel.php
  models/OrderModel.php
  views/elements/filters.php
  views/pages/ecommerce/coupon-list.php
  views/pages/ecommerce/order-list.php
Labels: v3

#831 TUTOR-course-content-api-integration
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/layouts/Header.tsx
  assets/react/v3/entries/course-builder/components/modals/CertificatePreviewModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/pages/Curriculum.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
Labels: v3

#832 Lesson details Ajax API
  classes/Lesson.php
Labels: v3

#833 Poster URL added to lesson details response
  classes/Lesson.php
Labels: v3

#811 Implemented the refund modal
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/entries/order-details/components/modals/RefundModal.tsx
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/atoms/CheckBox.tsx
  assets/react/v3/shared/components/fields/FormDateInput.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormInputWithContent.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/fields/FormTextareaInput.tsx
  assets/react/v3/shared/components/fields/FormTimeInput.tsx
  assets/react/v3/shared/utils/style-utils.ts
  assets/react/v3/shared/utils/validation.ts
  classes/Admin.php
Labels: v3

#819 Add mark as paid modal
  assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/components/fields/FormTextareaInput.tsx
Labels: v3

#821 Add cancel order modal
  assets/react/v3/entries/order-details/components/layout/Topbar.tsx
  assets/react/v3/entries/order-details/components/modals/CancelOrderModal.tsx
  assets/react/v3/shared/atoms/Alert.tsx
  assets/react/v3/shared/atoms/Avatar.tsx
Labels: v3

#822 Order mark as paid ajax api created
  ecommerce/OrderController.php
  helpers/QueryHelper.php
  models/OrderModel.php
Labels: v3

#836 Timezones added to course-builder _tutorobject
  classes/Course.php
  includes/tutor-general-functions.php
Labels: v3

#841 Lesson id passed to filter and remove rule for thumbnail_id
  classes/Lesson.php
Labels: v3

#842 Lesson modal content drip impemented
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/course-basic/ContentDripSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/layouts/Header.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/contexts/CourseDetailsContext.tsx
  assets/react/v3/entries/course-builder/pages/Curriculum.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
Labels: v3

#844 Tutor added as monetization list and refactor code
  classes/Tutor.php
  ecommerce/Ecommerce.php
  ecommerce/Init.php
Labels: v3

#843 Order net payment
  classes/Tutor.php
  models/OrderModel.php
Labels: v3

#840 Order meta Functionality
  classes/Tutor.php
  ecommerce/Ecommerce.php
  ecommerce/OrderActivitiesController.php
  ecommerce/OrderController.php
  models/OrderActivitiesModel.php
  models/OrderModel.php
Labels: v3

#845 Assignment api integration
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/CertificateCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingCard.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/layouts/Header.tsx
  assets/react/v3/entries/course-builder/components/modals/AddAssignmentModal.tsx
  assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
  assets/react/v3/entries/course-builder/components/modals/CertificatePreviewModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormCoursePrerequisites.tsx
  assets/react/v3/shared/components/fields/FormDateInput.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormSelectUser.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/config/styles.ts
  assets/react/v3/shared/molecules/DropdownButton.tsx
  assets/react/v3/shared/utils/form.ts
Labels: v3

#847 feat: Added Zoom meeting details query
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
Labels: v3

#839 Cart and Checkout pages design added
  assets/images/paypal.svg
  assets/images/stripe.svg
  assets/scss/front/_cart.scss
  assets/scss/front/_checkout.scss
  assets/scss/front/index.scss
  classes/Options_V2.php
  classes/Shortcode.php
  classes/Template.php
  classes/Upgrader.php
  classes/Utils.php
  templates/ecommerce/cart.php
  templates/ecommerce/checkout.php
Labels: v3

#851 Integrate backend api with the frontend
  assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/utils/endpoints.ts
Labels: v3

#849 Integrate order details api
  .gitignore
  assets/react/v3/declaration.d.ts
  assets/react/v3/entries/order-details/components/layout/Main.tsx
  assets/react/v3/entries/order-details/components/layout/Topbar.tsx
  assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/components/order/OrderBadge.tsx
  assets/react/v3/entries/order-details/components/order/OrderItem.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/components/order/PaymentBadge.tsx
  assets/react/v3/entries/order-details/components/order/Student.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/atoms/Avatar.tsx
  assets/react/v3/shared/utils/api.ts
  assets/react/v3/shared/utils/endpoints.ts
  assets/react/v3/shared/utils/url.ts
  assets/react/v3/shared/utils/util.ts
  composer.lock
Labels: v3

#848 Google Meet Details Api connected
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/shared/components/fields/FormInput.tsx
Labels: v3

#853 Integrate backend api for the order comment
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/utils/endpoints.ts
  ecommerce/OrderController.php
  models/OrderActivitiesModel.php
Labels: v3

#854 Add support for importing and exporting quizzes
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/shared/molecules/FileUploader.tsx
Labels: v3

#862 Quiz question delete API
  classes/Quiz.php
Labels: v3

#865 Question duplicate, update and answer sorting API
  classes/Quiz.php
Labels: v3

#867 :bug: Fix refund form inappropriate required rule issue
  assets/react/v3/entries/order-details/components/modals/RefundModal.tsx
Labels: v3

#866 Improve input field's focus design along with the error state.
  assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
  assets/react/v3/shared/components/fields/FormInputWithContent.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/fields/FormSelectUser.tsx
  assets/react/v3/shared/components/fields/FormTagsInput.tsx
  assets/react/v3/shared/molecules/DropdownButton.tsx
  assets/react/v3/shared/utils/style-utils.ts
  assets/react/v3/shared/utils/validation.ts
Labels: v3

#864 Improve the UX of the order cancelation form
  assets/react/v3/entries/order-details/components/modals/CancelOrderModal.tsx
Labels: v3

#863 Fix the discount modal's pricing calculation issue
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
Labels: v3

#860 :bug: fix an issue of the order summary design
  assets/react/v3/entries/order-details/components/App.tsx
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/components/order/Summary.tsx
  assets/react/v3/shared/atoms/Toast.tsx
  assets/react/v3/shared/utils/style-utils.ts
Labels: v3

#868 Tutor quiz save, update, sort and create question api integrated
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
  assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
Labels: v3

#869 Fix - deprecation warning in course builder
  .github/workflows/wpcs.yml
  classes/Course.php
Labels: v3

#871 Integrated Quiz Question update, duplicate and answer sorting API
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/components/fields/FormQuestionTitle.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/components/fields/quiz/FormTrueFalse.tsx
  assets/react/v3/shared/components/modals/Modal.tsx
  assets/react/v3/shared/molecules/ThreeDots.tsx
Labels: v3

#857 Integrate the refund modal with the backend api endpoint, update the queryHelper class.
  assets/react/v3/entries/order-details/components/modals/RefundModal.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/components/order/Student.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/atoms/CheckBox.tsx
  assets/react/v3/shared/utils/endpoints.ts
  ecommerce/OrderController.php
  helpers/QueryHelper.php
  models/OrderActivitiesModel.php
  models/OrderModel.php
Labels: v3

#872 Fix select field focus issue with error state
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
Labels: v3

#873 WPEditor component added
  assets/lib/prism/prism.css
  assets/lib/prism/prism.min.js
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/shared/atoms/WPEditor.tsx
  assets/react/v3/shared/components/fields/FormWPEditor.tsx
  classes/Course.php
  views/modal/wp-editor-link.php
  views/pages/course-builder.php
Labels: v3

#876 Create new answer api integrated
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/config/config.ts
  assets/react/v3/shared/config/icon-list.ts
  assets/react/v3/shared/utils/api.ts
Labels: v3

#880 Filter added to extend course builder localized data
  classes/Course.php
Labels: v3

#882 Fix - thumbnail is not removing
  classes/Course.php
  classes/Lesson.php
Labels: v3

#879 Quiz answer delete and mark as correct API integrated
  assets/react/v3/entries/course-builder/components/additional/CertificateCard.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/layouts/Navigator.tsx
  assets/react/v3/entries/course-builder/components/modals/CertificatePreviewModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormEditableAlias.tsx
  assets/react/v3/shared/components/fields/FormFileUploader.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
Labels: v3

#884 refactor: Update course settings form in CourseSettings component
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormMultiSelectInput.tsx
  assets/react/v3/shared/components/fields/FormRadioGroup.tsx
Labels: v3

#886 fix: fix Slect Product problem.
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
Labels: v3

#885 Course price save when monetize by tutor e-commerce
  classes/Course.php
  classes/Utils.php
  ecommerce/Ecommerce.php
Labels: v3

#892 Create question object added to response
  classes/Quiz.php
Labels: v3

#893 Tutor settings sidebar design improved
  views/options/settings.php
Labels: v3

#896 Quiz Answer creation flow update and fixed several bugs
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/pages/Curriculum.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/shared/atoms/CheckBox.tsx
  assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/components/fields/quiz/FormTrueFalse.tsx
  classes/Quiz.php
Labels: v3

#887 Courses list api for coupon applies to
  classes/Utils.php
  ecommerce/CouponController.php
  ecommerce/OrderController.php
  models/CouponModel.php
  models/CourseModel.php
Labels: v3

#889 Refund sorted with created date asc
  models/OrderModel.php
Labels: v3

#900 Order discount api
  ecommerce/OrderController.php
  models/OrderModel.php
Labels: v3

#883 Order cancel api & refund functionality update
  ecommerce/OrderActivitiesController.php
  ecommerce/OrderController.php
  models/OrderModel.php
Labels: v3

#901 EDD product list for course builder and additional data metabox removed
  classes/Course.php
  views/metabox/course-additional-data.php
Labels: v3

#903 Order cancel reason meta added
  ecommerce/OrderController.php
  models/OrderActivitiesModel.php
  models/OrderModel.php
Labels: v3

#905 Integrate discount modal with the backend api
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/services/order.ts
  assets/react/v3/shared/utils/currency.ts
  assets/react/v3/shared/utils/endpoints.ts
Labels: v3

#906 Order, Payment Settings & Manual Settings
  assets/react/admin-dashboard/segments/options.js
  classes/Options_V2.php
  classes/Utils.php
  ecommerce/Ecommerce.php
  ecommerce/OptionKeys.php
  ecommerce/OrderActivitiesController.php
  ecommerce/OrderController.php
  ecommerce/Settings.php
  models/OrderActivitiesModel.php
  models/OrderModel.php
  views/modal/ecommerce/add-manual-payment.php
  views/options/settings.php
  views/options/template/basic.php
Labels: v3

#904 Edd integration
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
Labels: v3

#907 Fix - EDD saved product not selected
  classes/Course.php
Labels: v3

#912 Ecommerce Settings, Custom Manual Payment & Add to Cart Functionalities
  assets/react/admin-dashboard/segments/options.js
  classes/Options_V2.php
  classes/Utils.php
  ecommerce/HooksHandler.php
  ecommerce/OptionKeys.php
  ecommerce/Settings.php
  includes/tutor-general-functions.php
  templates/loop/add-to-cart-tutor.php
  templates/loop/course-price-tutor.php
  templates/loop/course-price-woocommerce.php
  templates/single/course/add-to-cart-tutor.php
  views/modal/ecommerce/add-manual-payment.php
  views/modal/ecommerce/manual-payment.php
  views/options/option_blocks.php
  views/options/settings.php
  views/options/template/basic.php
Labels: v3

#908 Cart and Checkout pages functionalities added
  assets/react/front/pages/cart.js
  assets/react/front/pages/checkout.js
  assets/react/front/tutor-front.js
  assets/scss/front/_cart.scss
  assets/scss/front/_checkout.scss
  classes/Utils.php
  ecommerce/CartController.php
  ecommerce/Ecommerce.php
  models/CartModel.php
  templates/ecommerce/cart.php
  templates/ecommerce/checkout.php
Labels: v3

#909 Refactor: remove unused video meta-box and wp native list column
  classes/Course.php
  views/metabox/video-metabox.php
Labels: v3

#910 Fixed several issues in course builder and quiz builder
  assets/react/v3/entries/course-builder/components/additional/Certificate.tsx
  assets/react/v3/entries/course-builder/components/additional/LiveClass.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/GoogleMeetForm.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingCard.tsx
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/ImageAnswering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
  assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/atoms/WPEditor.tsx
  assets/react/v3/shared/components/fields/FormAnswerExplanation.tsx
  assets/react/v3/shared/components/fields/FormEditableAlias.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormQuestionDescription.tsx
  assets/react/v3/shared/components/fields/FormQuestionTitle.tsx
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
  assets/react/v3/shared/components/fields/FormSelectUser.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/components/fields/quiz/FormTrueFalse.tsx
  assets/react/v3/shared/molecules/ThreeDots.tsx
Labels: v3

#898 Improve the course builder navigator
  assets/react/v3/entries/course-builder/components/layouts/Navigator.tsx
  assets/react/v3/entries/course-builder/components/layouts/Tracker.tsx
  assets/react/v3/entries/course-builder/contexts/CourseNavigatorContext.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/shared/atoms/ProgressStep.tsx
  assets/react/v3/shared/utils/endpoints.ts
Labels: v3

#899 Update the axios config and set nonce from tutorobject
  assets/react/v3/entries/course-builder/components/subscription/PreviewItem.tsx
  assets/react/v3/shared/services/users.ts
  assets/react/v3/shared/utils/api.ts
  assets/react/v3/shared/utils/endpoints.ts
Labels: v3

#915 chore: Update delete topic popover title to use content title instead of topic title
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/shared/atoms/WPEditor.tsx
Labels: v3

#916 After creating a topic the Lesson Quiz buttons are not enabled.
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/shared/atoms/WPEditor.tsx
Labels: bug, v3

#917 🛠️ fix: Lesson preview switch field is linked with the lesson name field.
  assets/react/v3/entries/course-builder/components/additional/LiveClass.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
Labels: bug, v3

#918 🛠️ fix: Close modal after saving quiz changes
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
Labels: bug, v3

#919 🛠️ fix: True/false type question's correct answer selection is not working.
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
Labels: bug, v3

#921 Code refactor and removed unused course settings metabox
  classes/Course_Settings_Tabs.php
  views/metabox/settings-tabs.php
Labels: v3

#922 🛠️ fix: Showing Regular And Sale price when Subscription is created
  assets/react/v3/entries/course-builder/components/curriculum/QuestionForm.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/FillinTheBlanks.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
Labels: bug, v3

#926 Course builder editor support: Gutenberg, Droip, Elementor
  classes/Course.php
  classes/Quiz.php
  classes/Utils.php
Labels: v3

#923 Earnings & Commission Management
  classes/WooCommerce.php
  ecommerce/EarningController.php
  ecommerce/HooksHandler.php
  ecommerce/OrderController.php
  traits/EarningData.php
Labels: v3

#932 feat: implemeted functionality for cutom editor.
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/modals/EditorModal.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/course.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
Labels: v3

#931 WP Editor style improved
  assets/react/v3/shared/atoms/WPEditor.tsx
Labels: v3

#928 🛠️fix: Prevent user from switching to another question if none is selected as correct answer
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
Labels: bug, v3

#933 Refactor Earning Management
  classes/Earnings.php
  classes/WooCommerce.php
  ecommerce/HooksHandler.php
  traits/EarningData.php
Labels: v3

#934 Create draft course
  assets/react/front/dashboard/index.js
  assets/react/lib/tutor.js
  classes/Course.php
  classes/Dashboard.php
  classes/Utils.php
  views/pages/course-list.php
Labels: v3

#939 Plugin meta info updated
  readme.txt
  tutor.php
Labels: v2

#936 refactor: query revalidation logic
  assets/react/v3/entries/course-builder/components/curriculum/question-types/Matching.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/modals/EditorModal.tsx
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/components/RouteSuspense.tsx
  assets/react/v3/shared/components/fields/FormWPEditor.tsx
  assets/react/v3/shared/components/fields/quiz/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/fields/quiz/FormImageAnswering.tsx
  assets/react/v3/shared/components/fields/quiz/FormMatching.tsx
  assets/react/v3/shared/components/fields/quiz/FormMultipleChoiceAndOrdering.tsx
  assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
  assets/react/v3/shared/config/config.ts
Labels: v3

#941 refactor: Improve loading state handling in CourseBasic and Curriculum pages
  assets/react/v3/entries/course-builder/pages/CourseBasic.tsx
  assets/react/v3/entries/course-builder/pages/Curriculum.tsx
  classes/Quiz.php
Labels: bug, v3

#942 refactor: Add required validation for category name and parent category in FormCategoriesInput component
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/Topic.tsx
  assets/react/v3/entries/course-builder/pages/Curriculum.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
  assets/react/v3/shared/components/fields/FormWPEditor.tsx
  assets/react/v3/shared/utils/style-utils.ts
Labels: bug, v3
