Repository themeum/tutor, pull requests merged in 2025-08, with the labels that each got.

#2020 ✨ Refactor quiz question validation logic and imports
  assets/react/v3/entries/course-builder/components/curriculum/Question.tsx
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/entries/course-builder/contexts/QuizModalContext.tsx
  assets/react/v3/entries/course-builder/utils/utils.ts
  assets/react/v3/shared/utils/quiz.ts
Labels: refactor

#2031 🛠️ Integrate question conversion in QuestionList component
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
Labels: bug

#2036 New gift icon added
  assets/icons/gift.svg
  assets/react/v3/shared/icons/types.ts
  classes/Icon.php
Labels: 3.8.0

#1951 ✨ Migrate to RSPack
  .babelrc
  .gitignore
  .vscode/settings.json
  assets/react/v3/entries/addon-list/components/AddonList.tsx
  assets/react/v3/entries/addon-list/components/InstallationPopover.tsx
  gulpfile.js
  gulpfile.mjs
  package-lock.json
  package.json
  rspack.config.mjs
  v2-library/fonts/tutor-icon/tutor-icon.css
  v2-library/fonts/tutor-icon/tutor-icon.scss
  webpack.config.js
Labels: QoL

#2040 🧹 Remove unused dependencies from package.json
  package-lock.json
  package.json
Labels: QoL, refactor

#2034 🎉 WP Admin menu organization
  assets/scss/admin-dashboard/_tutor-admin.scss
  classes/Admin.php
  classes/WhatsNew.php
  ecommerce/AdminMenu.php
Labels: 3.8.0

#2029 Fix: Editor role cannot access wp post preview
  models/CourseModel.php
Labels: 3.8.0

#2047 Add new course icon to icon set
  assets/icons/course.svg
  assets/react/v3/shared/icons/types.ts
  classes/Icon.php
Labels: 3.8.0

#2051 🛠️ Fix course visibility validation based on pricing model
  assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
Labels: enhancement

#2052 Fix: wrong tax re-calculation for manual enrollment
  classes/Tutor.php
  classes/Upgrader.php
  ecommerce/OrderController.php
  models/OrderModel.php
Labels: 3.8.0

#2054 Refactor tutor-icon assets directory structure
  assets/scss/admin-dashboard/_tutor-admin.scss
  rspack.config.mjs
  v2-library/tutor-icon/fonts/tutor-v2.woff
  v2-library/tutor-icon/fonts/tutor.woff
  v2-library/tutor-icon/tutor-icon-demo.html
  v2-library/tutor-icon/tutor-icon.scss
  v2-library/tutor-icon/tutor-v2-icons.json
Labels: 3.8.0

#2056 🔧 Disable caching in base configuration
  rspack.config.mjs
Labels: bug

#2050 ✨ Add active subscription toggle
  assets/react/v3/shared/components/modals/SubscriptionModal.tsx
  assets/react/v3/shared/components/subscription/OfferSalePrice.tsx
  assets/react/v3/shared/components/subscription/PreviewItem.tsx
  assets/react/v3/shared/components/subscription/SubscriptionItem.tsx
  assets/react/v3/shared/components/subscription/SubscriptionPreview.tsx
  assets/react/v3/shared/services/subscription.ts
  classes/Shortcode.php
  classes/Template.php
Labels: 3.8.0

#2060 Fix RTL CSS file name in asset enqueuing
  classes/Assets.php
Labels: bug

#2061 ⚡ Refactor: Allow query helper methods to be called without table prefix
  helpers/QueryHelper.php
Labels: 3.8.0

#2062 ✨ Enhance subscription data structure and UI interactions
  assets/react/v3/shared/components/subscription/PreviewItem.tsx
  assets/react/v3/shared/components/subscription/SubscriptionPreview.tsx
  assets/react/v3/shared/services/subscription.ts
Labels: 3.8.0

#2069 New: query() method added to database query with flexible arguments.
  helpers/QueryHelper.php
Labels: 3.8.0

#2068 ✨ Enhance Button component with icon-only support and accessibility improvements
  assets/react/v3/entries/import-export/components/modals/CollectionList/CollectionListTable.tsx
  assets/react/v3/shared/atoms/Button.tsx
  assets/react/v3/shared/components/FocusTrap.tsx
  stories/atoms/Button.stories.tsx
Labels: enhancement, test, refactor

#2070 Models Added To Handle Order Item Meta, Cart Meta, Filter Hook & Refactors
  assets/react/helper/utils.js
  assets/react/v3/shared/icons/generate-icon-types.ts
  classes/Icon.php
  classes/Upgrader.php
  classes/WooCommerce.php
  ecommerce/HooksHandler.php
  ecommerce/OrderController.php
  models/CartItemModel.php
  models/CartModel.php
  models/OrderItemMetaModel.php
  models/OrderItemModel.php
  models/OrderModel.php
  readme.txt
  traits/JsonResponse.php
  tutor.php
Labels: 3.8.0
