Repository themeum/tutor, pull requests merged in 2025-07, with the labels that each got.

#1917 New filter design added
  assets/react/admin-dashboard/quiz-attempts.js
  assets/react/admin-dashboard/segments/filter.js
  classes/Instructors_List.php
  classes/Utils.php
  classes/Withdraw_Requests_List.php
  models/CourseModel.php
  v2-library/src/scss/components/_wp-dashboard-elements.scss
  views/elements/list-empty-state.php
  views/elements/list-navbar.php
  views/elements/navbar.php
  views/fragments/announcement-list.php
  views/pages/announcements.php
  views/pages/course-list.php
  views/pages/ecommerce/coupon-list.php
  views/pages/ecommerce/order-list.php
  views/pages/instructors.php
  views/pages/question_answer.php
  views/pages/quiz_attempts.php
  views/pages/students.php
  views/pages/withdraw_requests.php
  views/qna/qna-table.php
  views/quiz/attempt-table.php
Labels: 3.7.0

#1938 Tax warning design in course builder updated
  assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
  assets/react/v3/shared/components/fields/FormCheckbox.tsx
Labels: 3.7.0

#1935 Assignment with No Limit produce fatal error fixed
  templates/dashboard/assignments/submitted.php
Labels: 3.7.0

#1936 List design issue fixes
  assets/react/admin-dashboard/quiz-attempts.js
  cache/QuizAttempts.php
  classes/Q_And_A.php
  classes/Quiz_Attempts_List.php
  models/QuizModel.php
  views/fragments/announcement-list.php
  views/pages/question_answer.php
  views/qna/qna-table.php
  views/quiz/attempt-table.php
Labels: 3.7.0

#1940 Content bank updates
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicFooter.tsx
  assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/CollectionListTable.tsx
  assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/ContentListTable.tsx
  assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/index.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
  assets/react/v3/shared/components/modals/ConfirmationModal.tsx
  assets/react/v3/shared/services/content-bank.ts
  assets/react/v3/shared/utils/endpoints.ts
  assets/react/v3/shared/utils/types.ts
Labels: 3.7.0

#1944 ✨ Integrate Content Bank functionality in QuestionList and TopicFooter components
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicFooter.tsx
  assets/react/v3/entries/course-builder/services/quiz.ts
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/utils/types.ts
Labels: 3.7.0

#1945 🛠️ fix: added content bank question will be have `new` quiz data status
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
Labels: 3.7.0

#1933 {Instructor_feedback} placeholder in email trigger not woking fixed
  assets/react/lib/tutor.js
  classes/Quiz.php
Labels: 3.7.0

#1947 🛠️ Simplify handleCheckCorrectAnswer function in MultipleChoiceAndOrdering and TrueFalse components
  assets/react/v3/entries/course-builder/components/curriculum/question-types/MultipleChoiceAndOrdering.tsx
  assets/react/v3/entries/course-builder/components/curriculum/question-types/TrueFalse.tsx
Labels: 3.7.0

#1946 Set locale data support added for dynamic scripts
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/coupon-details/components/layout/Main.tsx
  assets/react/v3/entries/course-builder/config/routes.tsx
  classes/Assets.php
  classes/Course.php
  classes/Utils.php
  webpack.config.js
Labels: 3.7.0

#1953 ✨ feat: add size prop to Select and TextInput components
  assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/ContentListTable.tsx
  assets/react/v3/shared/atoms/Select.tsx
  assets/react/v3/shared/atoms/TextInput.tsx
  assets/react/v3/shared/molecules/Table.tsx
Labels: 3.7.0

#1954 Add responsive mobile menu for content bank collections
  assets/react/v3/shared/atoms/Button.tsx
  assets/react/v3/shared/atoms/TextInput.tsx
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/config/styles.ts
  assets/react/v3/shared/utils/style-utils.ts
Labels: 3.7.0

#1961 ✨ Update question ID generation and add translator comments
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/shared/utils/util.ts
Labels: 3.7.0

#1967 What's new page updated
  assets/scss/admin-dashboard/_whats-new.scss
  views/pages/whats-new.php
Labels: 3.7.0

#1970 🛠️ fix(tax-settings): improve handling of undefined values and defaults
  assets/react/v3/entries/tax-settings/components/TaxSettings.tsx
Labels: 3.7.0

#1971 ✨ feat: Enhance FocusTrap and Modal components with blur control props
  assets/react/v3/shared/components/FocusTrap.tsx
  assets/react/v3/shared/components/fields/quiz/FormQuestionTitle.tsx
  assets/react/v3/shared/components/modals/BasicModalWrapper.tsx
  assets/react/v3/shared/components/modals/ModalWrapper.tsx
Labels: 3.7.0

#1977 🔧 Update build scripts and dependencies
  assets/react/v3/shared/components/fields/quiz/questions/FormFillinTheBlanks.tsx
  assets/react/v3/shared/components/modals/ProIdentifierModal.tsx
  assets/react/v3/shared/utils/validation.ts
  eslint.config.mjs
  package-lock.json
  package.json
Labels: 3.7.0, QoL

#1979 ✨ Enhance export functionality and improve state management
  assets/react/v3/entries/import-export/components/Export.tsx
  assets/react/v3/entries/import-export/components/modals/CollectionList/CollectionListTable.tsx
  assets/react/v3/entries/import-export/components/modals/CollectionList/SearchField.tsx
  assets/react/v3/entries/import-export/components/modals/CollectionList/index.tsx
  assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ExportContentBankState.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
  assets/react/v3/shared/utils/url.ts
Labels: 3.7.0

#1980 Simplified @OrderDetails and @CouponDetails aliases
  assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
  assets/react/v3/entries/coupon-details/components/coupon/CouponInfo.tsx
  assets/react/v3/entries/coupon-details/components/coupon/CouponLimitation.tsx
  assets/react/v3/entries/coupon-details/components/coupon/CouponPreview.tsx
  assets/react/v3/entries/coupon-details/components/coupon/CouponValidity.tsx
  assets/react/v3/entries/coupon-details/components/coupon/PurchaseRequirements.tsx
  assets/react/v3/entries/coupon-details/components/layout/Main.tsx
  assets/react/v3/entries/coupon-details/components/layout/MainContent.tsx
  assets/react/v3/entries/coupon-details/components/layout/Topbar.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/CategoryListTable.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/CourseListTable.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/MembershipPlanListTable.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/index.tsx
  assets/react/v3/entries/coupon-details/index.tsx
  assets/react/v3/entries/order-details/components/layout/Main.tsx
  assets/react/v3/entries/order-details/components/layout/Topbar.tsx
  assets/react/v3/entries/order-details/components/modals/CancelOrderModal.tsx
  assets/react/v3/entries/order-details/components/modals/DiscountModal.tsx
  assets/react/v3/entries/order-details/components/modals/MarkAsPaidModal.tsx
  assets/react/v3/entries/order-details/components/modals/RefundModal.tsx
  assets/react/v3/entries/order-details/components/order/Activities.tsx
  assets/react/v3/entries/order-details/components/order/Notes.tsx
  assets/react/v3/entries/order-details/components/order/OrderBadge.tsx
  assets/react/v3/entries/order-details/components/order/OrderItem.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
  assets/react/v3/entries/order-details/components/order/PaymentBadge.tsx
  assets/react/v3/entries/order-details/components/order/PaymentInfo.tsx
  assets/react/v3/entries/order-details/components/order/Student.tsx
  assets/react/v3/entries/order-details/components/order/Summary.tsx
  assets/react/v3/entries/order-details/contexts/order-context.tsx
  assets/react/v3/entries/order-details/index.tsx
  tsconfig.json
  webpack.config.js
Labels: 3.7.0

#1985 ✨ Refactor export modal and initial state handling
  assets/react/v3/entries/import-export/components/modals/CollectionList/CollectionListTable.tsx
  assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
Labels: 3.7.0

#1986 ✨ Refactor Tooltip to include zIndex prop for improved layering control
  assets/react/v3/shared/atoms/Tooltip.tsx
Labels: 3.7.0

#1992 ✨ [TEST] Enhance filtering and search functionality across tests
  cypress/e2e/backend/announcements.cy.ts
  cypress/e2e/backend/assignments.cy.ts
  cypress/e2e/backend/coupons.cy.ts
  cypress/e2e/backend/courses.cy.ts
  cypress/e2e/backend/enrollment.cy.ts
  cypress/e2e/backend/google-meet.cy.ts
  cypress/e2e/backend/gradebook.cy.ts
  cypress/e2e/backend/instructors.cy.ts
  cypress/e2e/backend/question-answer.cy.ts
  cypress/e2e/backend/quiz-attempts.cy.ts
  cypress/e2e/backend/withdraw-request.cy.ts
  cypress/e2e/backend/zoom.cy.ts
  cypress/e2e/frontend/dashboard/instructor-announcements.cy.ts
  cypress/e2e/frontend/dashboard/instructor-quiz-attempts.cy.ts
  cypress/e2e/frontend/dashboard/instructor-zoom.cy.ts
  cypress/e2e/frontend/dashboard/student-my-quiz-attempts.cy.ts
  cypress/e2e/frontend/dashboard/student-order-history.cy.ts
  cypress/e2e/frontend/dashboard/student-question-answer.cy.ts
  cypress/support/auth.ts
  cypress/support/commands.ts
Labels: test

#1996 Bundle filter issue fixed when no items available
  classes/Course_List.php
  classes/Utils.php
  views/pages/course-list.php
Labels: bug

#1995 Display only approved ratings in instructors profile
  classes/Utils.php
Labels: bug

#1997 🔧 Enhance hasAnyCourseWithChildren function for course-bundle support
  assets/react/v3/entries/import-export/utils/utils.ts
Labels: 3.7.0

#2003 Simplify and update supported social networks
  assets/lib/SocialShare/SocialShare.js
  assets/lib/SocialShare/SocialShare.min.js
Labels: 3.7.1

#2000 Fix: Added filter hook for updating query
  models/CourseModel.php
Labels: 3.7.1

#2006 ✨ Refactor course management components and imports
  assets/react/v3/entries/import-export/components/modals/CollectionList/index.tsx
  assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
  assets/react/v3/entries/import-export/services/import-export.ts
  assets/react/v3/shared/components/modals/CourseListModal/CourseListTable.tsx
  assets/react/v3/shared/components/modals/CourseListModal/SearchField.tsx
  assets/react/v3/shared/components/modals/CourseListModal/index.tsx
  assets/react/v3/shared/services/import-export.ts
  assets/react/v3/shared/utils/endpoints.ts
Labels: 3.7.1

#2005 pinterest added to the social share
  assets/lib/SocialShare/SocialShare.js
  assets/lib/SocialShare/SocialShare.min.js
Labels: 3.7.1

#2012 ✨ Refactor exportable content handling with course_ids parameter
  assets/react/v3/entries/import-export/components/modals/ExportModal.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ExportInitialState.tsx
  assets/react/v3/entries/import-export/components/modals/import-export-states/ImportInitialState.tsx
  assets/react/v3/shared/services/import-export.ts
Labels: 3.7.1

#2015 Add content type badges to content list table
  assets/react/v3/entries/course-builder/components/modals/ContentBankContentSelectModal/ContentListTable.tsx
Labels: 3.7.1
