Repository themeum/tutor, pull requests merged in 2025-04, with the labels that each got.

#1696 ✨ Integrate FormQuestion components and enhance editing features in QuizModal
  assets/react/v3/entries/course-builder/components/curriculum/QuestionList.tsx
  assets/react/v3/entries/course-builder/components/fields/FormQuestionDescription.tsx
  assets/react/v3/entries/course-builder/components/fields/FormQuestionTitle.tsx
  assets/react/v3/entries/course-builder/components/modals/QuizModal.tsx
  assets/react/v3/shared/atoms/WPEditor.tsx
  assets/react/v3/shared/components/fields/FormWPEditor.tsx
Labels: v3.4.x

#1697 🛠️ Refactor supportRandomize question types by removing 'ordering'
  assets/react/v3/entries/course-builder/components/curriculum/QuestionConditions.tsx
  templates/single/quiz/parts/question.php
Labels: v3.4.x

#1704 ✨Reactor FormSelectInput Disable logic and initial value retrieval
  assets/react/v3/shared/components/fields/FormSelectInput.tsx
Labels: v3.4.x

#1707 ✨ fix: improve date parsing and update react-day-picker dependency
  assets/react/v3/shared/components/fields/FormDateInput.tsx
  package-lock.json
  package.json
Labels: v3.5.x

#1699 ✨ Add membership plans and enhance coupon management functionality
  assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
  assets/react/v3/entries/coupon-details/components/layout/Main.tsx
  assets/react/v3/entries/coupon-details/components/layout/Topbar.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/MembershipPlanListTable.tsx
  assets/react/v3/entries/coupon-details/components/modals/CourseListModal/index.tsx
  assets/react/v3/entries/coupon-details/services/coupon.ts
  assets/react/v3/shared/config/config.ts
  assets/react/v3/shared/services/subscription.ts
  assets/react/v3/shared/utils/types.ts
  assets/react/v3/shared/utils/util.ts
Labels: v3.5.x

#1701 🛠️ Prevent `coupon_type` from changing and validation added for specific_courses/bundles/categories type coupon
  ecommerce/CouponController.php
Labels: v3.4.x

#1721 Store customer billing info for each order
  ecommerce/HooksHandler.php
  models/OrderModel.php
Labels: v3.5.x

#1723 ✨ Enhance formatSubscriptionRepeatUnit for readability and singular support
  assets/react/v3/shared/utils/util.ts
Labels: v3.5.x

#1716 🎉 Membership trial feature
  assets/scss/front/_checkout.scss
  classes/Earnings.php
  ecommerce/CheckoutController.php
  ecommerce/HooksHandler.php
  ecommerce/OrderController.php
  includes/translate-text.php
  models/OrderModel.php
  templates/dashboard/purchase_history.php
  templates/ecommerce/checkout-details.php
  templates/ecommerce/checkout.php
Labels: v3.5.x

#1725 🛠️ Fix membership plans value in appliesToOptions
  assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
Labels: v3.5.x

#1728 ✨ Enhance coupon functionality for membership plans
  assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
  assets/react/v3/entries/coupon-details/components/layout/Main.tsx
  assets/react/v3/entries/coupon-details/services/coupon.ts
Labels: v3.5.x

#1731 🛠️ Fix membership plans logic in coupon discount options
  assets/react/v3/entries/coupon-details/components/coupon/CouponDiscount.tsx
Labels: v3.5.x

#1729 Fix: Assignment submission and deadline based on content drip settings
  classes/Utils.php
  templates/single/assignment/content.php
Labels: v3.5.x

#1733 ✨ Refactor category and tag setup with term ID validation
  classes/Course.php
Labels: v3.5.x

#1719 ✨ Search feature in Course Builder Categories Input
  assets/react/v3/shared/atoms/CheckBox.tsx
  assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
  assets/react/v3/shared/components/fields/FormFieldWrapper.tsx
  assets/react/v3/shared/components/fields/FormMultiLevelSelect.tsx
  assets/react/v3/shared/components/fields/FormSelectUser.tsx
  assets/react/v3/shared/services/category.ts
Labels: v3.5.x

#1724 🎥 [TEST] Enhance video URL handling in course media configuration
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  cypress/e2e/course-builder/02-course-settings.cy.ts
Labels: v3.5.x

#1730 ✨ Enhance visibility control for course components and settings options
  assets/react/v3/@types/index.d.ts
  assets/react/v3/entries/course-builder/components/additional/LiveClass.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseBasicSidebar.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CoursePricing.tsx
  assets/react/v3/entries/course-builder/components/course-basic/CourseSettings.tsx
  assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
  assets/react/v3/entries/course-builder/pages/Additional.tsx
  assets/react/v3/shared/atoms/SVGIcon.tsx
  assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
  assets/react/v3/shared/components/fields/FormFileUploader.tsx
  assets/react/v3/shared/components/fields/FormImageInput.tsx
  assets/react/v3/shared/components/fields/FormInput.tsx
  assets/react/v3/shared/components/fields/FormInputWithContent.tsx
  assets/react/v3/shared/components/fields/FormSelectUser.tsx
  assets/react/v3/shared/components/fields/FormSwitch.tsx
  assets/react/v3/shared/components/fields/FormTagsInput.tsx
  assets/react/v3/shared/components/fields/FormTextareaInput.tsx
  assets/react/v3/shared/components/fields/FormVideoInput.tsx
  assets/react/v3/shared/config/constants.ts
  assets/react/v3/shared/hoc/withVisibilityControl.tsx
  assets/react/v3/shared/hooks/useVisibilityControl.tsx
  assets/react/v3/shared/utils/types.ts
Labels: v3.5.x

#1742 Per order billing information save issue fixed
  ecommerce/HooksHandler.php
  models/OrderModel.php
Labels: v3.5.x

#1738 🔧 Fix input types and handle empty quiz options
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
  assets/react/v3/entries/course-builder/components/curriculum/TopicContent.tsx
  assets/react/v3/entries/course-builder/services/quiz.ts
Labels: v3.5.x

#1743 💳 Add `net-payment` condition to handle PaymentActionButton
  assets/react/v3/entries/order-details/components/order/OrderItem.tsx
  assets/react/v3/entries/order-details/components/order/Payment.tsx
Labels: v3.5.x

#1744 Update: new hook for adding badge for bundle
  templates/dashboard/my-courses.php
Labels: v3.5.x

#1739 🆕 : Paddle
  assets/react/front/pages/checkout.js
  templates/dashboard/purchase_history.php
  templates/ecommerce/checkout-details.php
Labels: v3.5.x

#1741 Update: Instructor list shortcode category filter
  classes/Shortcode.php
Labels: v3.5.x

#1737 New filter and navbar introduced in course list page
  assets/fonts/tutor-v2.woff
  assets/react/admin-dashboard/segments/filter.js
  assets/react/lib/sorting.js
  assets/scss/admin-dashboard/_tutor-admin.scss
  v2-library/fonts/fonts/tutor-v2.woff
  v2-library/fonts/tutor-icon/tutor-icon-demo.html
  v2-library/fonts/tutor-icon/tutor-icon.css
  v2-library/fonts/tutor-icon/tutor-v2-icons.json
  v2-library/src/js/popupMenu.js
  v2-library/src/scss/components/_meta.scss
  v2-library/src/scss/components/_wp-dashboard-elements.scss
  v2-library/src/scss/elements/_buttons.scss
  v2-library/src/scss/elements/_input.scss
  views/elements/course-filters.php
  views/elements/course-navbar.php
  views/pages/course-list.php
  views/pages/ecommerce/coupon-list.php
  views/pages/ecommerce/order-list.php
Labels: v3.5.x

#1745 🛠️ Simplify character limit validation and enhance input help text
  assets/react/v3/entries/course-builder/components/curriculum/QuizSettings.tsx
Labels: v3.5.x

#1726 Fix: Prevent scheduled course preview of other instructor
  classes/Course.php
Labels: v3.5.x

#1746 ✏️ Fix typo in visibility control key for course materials
  assets/react/v3/shared/config/constants.ts
Labels: v3.5.x

#1748 Fixed The _load_textdomain_just_in_time Notice Error
  classes/Admin.php
  classes/Announcements.php
  classes/Course_List.php
  classes/Course_Widget.php
  classes/Instructors_List.php
  classes/Quiz_Attempts_List.php
  classes/Students_List.php
  classes/Tutor.php
  classes/Withdraw_Requests_List.php
  ecommerce/CouponController.php
  ecommerce/OrderController.php
Labels: v3.5.x, 3.5.0

#1750 New: updated my-courses and added hook to use course bundle filter
  templates/dashboard/my-courses.php
Labels: 3.5.0

#1755 🔧 fix: update dropdown visibility condition to show when items are available
  assets/react/v3/entries/course-builder/components/layouts/header/HeaderActions.tsx
Labels: v3.5.x

#1756 ✨ fix: update renderInLastRow type and clean up table styles
  assets/react/v3/shared/molecules/Table.tsx
Labels: v3.5.x

#1766 Fix: Show empty category field changed to hide empty category
  classes/Shortcode.php
Labels: 3.5.0

#1769 Fix(🛠️) : Ajax was calling multiple times
  assets/react/front/pages/checkout.js
Labels: 3.5.0

#1771 Fix: can user edit course check logic not correctly implement
  classes/Utils.php
Labels: 3.5.0

#1770 Fix(🛠️) : deduct fees will be zero if it's greater than total_price.
  classes/Earnings.php
Labels: 3.5.0

#1773 🔧 Prevent search display when input is disabled
  assets/react/v3/shared/components/fields/FormCategoriesInput.tsx
Labels: v3.5.x

#1774 ✨ Enhance LessonModal Layout with visibility controls
  assets/react/v3/entries/course-builder/components/modals/LessonModal.tsx
Labels: v3.5.x

#1775 ✨ feat: enhance category list tree generation logic
  assets/react/v3/shared/utils/util.ts
Labels: v3.5.x

#1776 ✨ Enhance category filtering in generateTree function
  assets/react/v3/shared/components/fields/FormMultiLevelSelect.tsx
  assets/react/v3/shared/utils/util.ts
Labels: v3.5.x

#1781 🛠️ Fix meeting date formatting
  assets/react/v3/entries/course-builder/components/additional/meeting/ZoomMeetingForm.tsx
  assets/react/v3/entries/course-builder/components/course-basic/ScheduleOptions.tsx
Labels: v3.5.x

#1783 Fix: Depreciation warning for nullable default parameters in php 8.4
  classes/Utils.php
  helpers/DateTimeHelper.php
  traits/JsonResponse.php
Labels: 3.5.0

#1785 Always actual fees will be inserted.
  classes/Earnings.php
Labels: 3.5.0
