Repository themeum/tutor, pull requests merged in 2025-09, with the labels that each got.

#2079 Refine template import UI and preview modal styles
  assets/react/admin-dashboard/template-import-script.js
  assets/scss/admin-dashboard/template-import.scss
  views/template-import/templates.php
Labels: 3.8.0

#2089 Gift meta keys added to the order details
  assets/react/v3/entries/order-details/components/order/OrderItem.tsx
  assets/react/v3/entries/order-details/services/order.ts
  models/OrderModel.php
Labels: 3.8.0

#2098 Fixed: Backslash is showing in certificate's authorised name
  assets/react/v3/entries/payment-settings/components/PaymentItem.tsx
  assets/react/v3/entries/payment-settings/components/modals/ManualPaymentModal.tsx
  assets/react/v3/shared/atoms/WPEditor.tsx
  assets/react/v3/shared/components/modals/Modal.tsx
  classes/Options_V2.php
  classes/Utils.php
  ecommerce/Settings.php
  ecommerce/Tax.php
Labels: 3.8.2

#2107 🛠️ Fix CSS for last-child border in email datatable
  templates/email/email_styles.php
Labels: bug

#2113 Fix: show total marks based on final grade calculation settings
  templates/single/quiz/previous-attempts.php
  views/quiz/attempt-table.php
  views/quiz/header-context/course-single-previous-attempts.php
Labels: 3.8.2

#2103 Latex not displaying properly in quiz attempt details fixed
  assets/scss/modules/quiz-attempts.scss
  views/quiz/attempt-details.php
Labels: 3.8.2

#2118 🆕 : New function to update meta data to sync tutor course and woocommerce product
  classes/Course.php
  models/CourseModel.php
Labels: 3.8.2

#2120 Fix password toggle button style issue in FormInput
  assets/react/v3/shared/components/fields/FormInput.tsx
Labels: bug

#2122 Fix: multiple enrollment and earning record adding for WC subscription
  classes/WooCommerce.php
Labels: 3.8.2

#2119 Fix(🛠️) : Deprecation message in checkout.
  ecommerce/PaymentGateways/Configs/PaypalConfig.php
  ecommerce/PaymentGateways/GatewayBase.php
Labels: 3.8.2

#2123 Refactored `feedback_mode` to `is_retry_allowed`
  assets/react/v3/entries/course-builder/components/modals/AssignmentModal.tsx
  assets/react/v3/entries/course-builder/services/curriculum.ts
Labels: 3.8.2

#2116 New design added for order success and failed
  assets/images/orders/order-confirmed.svg
  assets/images/orders/payment-failed.svg
  assets/scss/front/_order.scss
  assets/scss/front/index.scss
  templates/ecommerce/order-placement-failed.php
  templates/ecommerce/order-placement-success.php
Labels: 3.8.2
